server:
  port: 8082
  max-http-header-size: 10MB
  
spring:
  application:
    name: ms-core-batch-extractor

  main:
    allow-bean-definition-overriding: true
  batch:
    initialize-schema: ALWAYS

  mail:
    host: ${MAIL_HOST:smtpl.royalairmaroc.com}
    port: ${MAIL_PORT:25}
    username: ${MAIL_USER:venga@royalairmaroc.com}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: true
        debug: true
    protocol: smtp
    test-connection: false
    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URI:http://kck.test.app.royalairmaroc.com:8080}/auth/realms/vtg

  thymeleaf:
    enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/venga}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:venga}

    dbcp2:
      max-wait-millis: 30000
      validation-query: SELECT 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true

  liquibase:
    enabled:  false
    change-log: classpath:/liquibase/db/migration/db.changelog.oracle.master.xml
  data:
    web:
      pageable:
        default-page-size: 10

springdoc:
  pathsToMatch: /api/**

# DEFAULT : Service discovry Config -------------------------------------   
eureka: 
  instance:
    hostname: eureka-server
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://${EUREKA_URI:localhost}:${EUREKA_PORT:8761}/eureka/

#keycloak
keycloak:
  cors: true
  cors-allowed-methods: POST, PUT, DELETE, GET, OPTIONS
  cors-allowed-headers: X-Requested-With, Content-Type, Authorization, Origin, Accept, Access-Control-Request-Method, Access-Control-Request-Headers, Access-Control-Allow-Origin
  auth-server-url: ${KEYCLOAK_URI:http://kck.test.app.royalairmaroc.com:8080}/auth
  realm: vtg
  resource: venga
  credentials:
    secret: Op4PaJ4bE9B1ITNFr4wtPSPUckuZSwIH
  ssl-required: none
  # principal-attribute: preferred_username
  policy-enforcer-config:
    paths:
      - name: insecure Resource
        path: /job/*
        enforcement-mode: DISABLED
  securityConstraints:
    - auth-roles:
        - "*"
      securityCollections:
        - name:
          patterns:
            - /api/v1/*
 # principal-attribute: preferred_username
 # policy-enforcer-config:
 #   enforcement-mode: ENFORCING

 # securityConstraints[0]:
  #  authRoles[0]: '*'
  #  securityCollections[0]:
  #    patterns[0]: /*
#keycloak-add-on:
 # unprotectedpaths: ${KEYCLOAK_UNPROTECTED_PATHS:/api/auth/**, /actuator/**, /v3/api-docs/**, /swagger-resources/webjars/**,/webjars/**/*, /swagger-ui.html, /swagger-resources/**}
logging:
  level:
  #  root: DEBUG
    org.keycloak: DEBUG
    com.ram.venga: DEBUG

batch:
  url: http://localhost:8090/api/batch
  venteElementExtraction: /process/venteElement
  processVente: /process/vente
  writeVente: /write/vente
  transportElementExtraction: /process/transportElement
  processTransport: /process/transport
  writeTransport: /write/transport
  rapprochement: /rapprochement
  writeVenteOne: /write/vente/one
  writeTransportOne: /write/transport/one
  sendEmail: /send/emailWarning

app:
  resources: C:\venga\devops-venga\appResources\
  ArchivePath: C:\venga\devops-venga\appResources\archived\


scheduled:
  transport: 0 0 0 L * ?
  vente: 0 0 6,14 * * ?

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
