server:
  port: 8090

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ms-core-gateway
    
  cloud:
    gateway:
      routes:
      - id: business
        uri: ${ENV_URI}:8089
        predicates:
        - Path=/api/**
        - Method=GET,POST,DELETE,PUT,OPTIONS
        filters:
        - RemoveRequestHeader=Cookie
        - AddRequestHeader=second-request, second-request-header
        
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URI}/auth/realms/vtg
          
      client:
        provider:
          keycloak:
            authorization-uri: ${KEYCLOAK_URI}/auth/realms/vtg/protocol/openid-connect/auth
            user-info-uri: ${KEYCLOAK_URI}/auth/realms/vtg/protocol/openid-connect/userinfo
            issuer-uri: ${KEYCLOAK_URI}/auth/realms/vtg
            user-name-attribute: preferred_username
        registration:
          tat-realm:
            provider: keycloak
            client-id: venga
            client-secret: Op4PaJ4bE9B1ITNFr4wtPSPUckuZSwIH
            authorization-grant-type: authorization_code
            scope: openid,profile,email   

# DEFAULT : Service discovry Config ------------------------------------- 
eureka:
  instance:
    hostname: eureka-server
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URI}:${EUREKA_PORT:8761}/eureka/
              
port:
  front-end: 3000
host:
  front-end: ${ENV_URI}

