server:
  port: 8090
  max-http-header-size: 10MB

spring:
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USER:venga@royalairmaroc.com}
    
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: true
   #     debug: true
    protocol: smtp
    test-connection: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URI:http://kck.test.app.royalairmaroc.com:8080}/auth/realms/vtg

  application:
    name: ms-venga-business
  main:
    allow-bean-definition-overriding: true
  batch:
    initialize-schema: ALWAYS

  thymeleaf:
    enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/venga}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:venga}

    dbcp2:
      max-wait-millis: 30000
      validation-query: SELECT 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true

  liquibase:
    enabled:  true
    change-log: classpath:/liquibase/db/migration/db.changelog.oracle.master.xml
  data:
    web:
      pageable:
        default-page-size: 10
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

springdoc:
  enable-native-support: true
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha
    oauth:
      client-secret: YTr0qQ2btKX4GC8XfDNKfI1cirK4E
      client-id: venga
  pathsToMatch: /api/**

# DEFAULT : Service discovry Config -------------------------------------   
eureka:
  instance:
    hostname: eureka-server
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://${EUREKA_URI:localhost}:${EUREKA_PORT:8761}/eureka/

#keycloak
keycloak:
  cors: true
  cors-allowed-methods: POST, PUT, DELETE, GET, OPTIONS
  cors-allowed-headers: X-Requested-With, Content-Type, Authorization, Origin, Accept, Access-Control-Request-Method, Access-Control-Request-Headers, Access-Control-Allow-Origin
  auth-server-url: ${KEYCLOAK_URI:http://localhost:8080}/auth
  realm: vtg
  resource: venga
  credentials:
    secret: efc2c1bd-18e1-404f-bb11-6a5573457c8a
  ssl-required: none
  # principal-attribute: preferred_username
  policy-enforcer-config:
    enforcement-mode: ENFORCING
    paths:
      - name: insecure Resource
        path: /api/auth/*
        enforcement-mode: DISABLED

      - name: insecure process batch Resource
        path: /api/batch/process/*
        enforcement-mode: DISABLED

      - name: insecure write batch Resource
        path: /api/batch/write/*
        enforcement-mode: DISABLED

      - name: insecure write one Resource
        path: /api/batch/write/vente/*
        enforcement-mode: DISABLED

      - name: swagger UI
        path: /swagger-ui/*
        enforcement-mode: DISABLED

      - name: all swagger-resources webjars resources
        path: /swagger-resources/webjars/*
        enforcement-mode: DISABLED

      - name: all webjars resources
        path: /webjars/*
        enforcement-mode: DISABLED

      - name: all configuration resources
        path: /configuration/ui
        enforcement-mode: DISABLED

      - name: all swagger-resources resources
        path: /swagger-resources/*
        enforcement-mode: DISABLED

      - name: all images resources
        path: /images/*
        enforcement-mode: DISABLED

      - name: all docs resources
        path: /v2/api-docs
        enforcement-mode: DISABLED

      - name: insecure rapprochement batch Resource
        path: /api/batch/rapprochement
        enforcement-mode: DISABLED

      - name: insecure updateVenteNonIntegre  Resource
        path: /api/batch/updateVenteNonIntegre
        enforcement-mode: DISABLED

      - name: insecure updateRecetteNonIntegre  Resource
        path: /api/batch/updateRecetteNonIntegre
        enforcement-mode: DISABLED

      - name: insecure nonRapprocherParErreur  Resource
        path: /api/batch/Vente/nonRapprocherParErreur
        enforcement-mode: DISABLED

      - name: insecure archivage-date-vente  Resource
        path: /api/batch/archivage-date-vente
        enforcement-mode: DISABLED

      - name: insecure keycloack  Resource
        path: /api/v1/keycloack/create-referencial-users
        enforcement-mode: DISABLED

      - name: insecure deletye  Resource
        path: /api/v1/keycloack/delete-referencial-users
        enforcement-mode: DISABLED

      - name: insecure send emailWarning  Resource
        path: /api/batch/send/emailWarning
        enforcement-mode: DISABLED

      - name: insecure validate otp  Resource
        path: /api/otp/validate
        enforcement-mode: DISABLED

      - name: insecure vente save  Resource
        path: /api/batch/job/vente
        enforcement-mode: DISABLED

      - name: insecure transport save  Resource
        path: /api/batch/job/transport
        enforcement-mode: DISABLED


      - name: insecure info user  Resource
        path: /api/v1/user/Info
        enforcement-mode: DISABLED

  securityConstraints:
    - auth-roles:
        - "*"
      securityCollections:
        - name:
          patterns:
            - /api/v1/*
            - /api/otp/*
    - auth-roles: [ ]
      securityCollections:
        - name:
          patterns:
            - /api/otp/validate
            - /api/batch/archivage-date-vente
            - /api/batch/Vente/nonRapprocherParErreur
            - /webjars/*
            - /configuration/ui
            - /swagger-resources/*
            - /images/*
            - /v2/api-docs
            - /api/batch/rapprochement
            - /api/batch/updateVenteNonIntegre
            - /api/batch/updateRecetteNonIntegre
            - /api/auth/*
            - /api/batch/process/*
            - /api/batch/write/*
            - /api/batch/write/vente/*
            - /swagger-ui/*
            - /swagger-resources/webjars/*
            - /api/v1/keycloack/create-referencial-users
            - /api/v1/keycloack/delete-referencial-users
            - /api/batch/send/emailWarning
            - /api/v1/user/Info

 # principal-attribute: preferred_username
  #  policy-enforcer-config:
  #   enforcement-mode: ENFORCING

  # securityConstraints[0]:
  #  authRoles[0]: '*'
  #  securityCollections[0]:
  #    patterns[0]: /*
  #keycloak-add-on:
  # unprotectedpaths: ${KEYCLOAK_UNPROTECTED_PATHS:/api/auth/**, /actuator/**, /v3/api-docs/**, /swagger-resources/webjars/**,/webjars/**/*, /swagger-ui.html, /swagger-resources/**}
logging:
  level:
    #  root: DEBUG
    org:
     # keycloak: DEBUG

frontend:
  server:
    url: ${ENV_URI:http://vtg.test.app.royalairmaroc.com}

user:
  admin:
    usernameAdmin: ${usernameAdmin:admin}
    passwordAdmin: ${password:rwLnYIQYFnzwnQtNEwc1}

helper:
  setFrom: ${setfrom:no-reply@venga.com}
  personal: ${setfrom:venga}

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000

app:
  resources: C:\venga\devops-venga\appResources\
  ArchivePath: C:\venga\devops-venga\appResources\archived\

directories:
  excelFilesPath : C:\venga\devops-venga\appResources\
  excelFilesArchivePath : C:\venga\devops-venga\appResources\archived\

mois:
  archivage: 12


scheduled:
  archivage: 0 1 * * * ?

otp:
  validity-duration-minutes: 5


